### PR TITLE
fix(skip-job): allow skip-job to work with parameters

### LINKED ISSUE #6: SKIP_JOB parameters
If a package workflow triggers a job that is defined in the package's `circle.yml` with parameters and that job is skipped it will fail since the workflow is calling `SKIP_JOB` with parameters that `SKIP_JOB` doesn't accept.

Proposed: Instead of outright replacing the job with `SKIP_JOB`, add the job's parameters into `SKIP_JOB`
https://github.com/circletron/circletron/blob/f6a67ce915d37cbf364ecca13269c2d8482fa814/src/index.ts#L205
```js
jobsConfig[jobName] = triggerPackages.has(pkg.name) ? jobData : { ...SKIP_JOB, parameters: jobData.parameters }
```

Current workaround: duplicate the job with the parameter hard-coded.

### PR DESCRIPTION
**Pull request by TheSharpieOne**
allow skip-job to work with parameters

fixes #6

### CODE REVIEW

**Review by insidewhy — APPROVED** [review]

File: src/index.ts [hunk 1]
```diff
@@ -188,7 +188,7 @@ async function buildConfiguration(
     mergeObject('commands', circleConfig)
 
     // jobs may be missing from circle config if all workflow jobs are from orbs
-    const jobs = circleConfig.jobs as Record<string, { conditional?: boolean }>
+    const jobs = circleConfig.jobs as Record<string, { conditional?: boolean, parameters?: {} }>
```
Comment (insidewhy) [inline src/index.ts:191]: I think `Record<string, any>` is the recommended way to do this now instead of `{}`.

**Comment by insidewhy** [comment]
@TheSharpieOne Released 3.0.5 with this fix.
